Refactoring
Khaled-AlKhateeb/math-magicians pull request #4
Opened 2022-10-27 12:41 UTC by Khaled-AlKhateeb

##Tasks Done ✔️ 

- Refactored the Calculator component from a class based component to a functional component with hooks.

2022-10-27 13:30 UTC, prolajumokeoni requested changes
Hi @Khaled-AlKhateeb 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used 



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 13:30 UTC, prolajumokeoni commented on src/components/Calculator.js
> +  };
- [ ] Please ensure that your app still works properly after the refactoring from class to functional-based components, currently when your app starts it shows a blank page

![Screenshot_512](https://user-images.githubusercontent.com/69638013/198297606-6ca2b129-c79c-49c2-97c0-7595caadca5e.png)

2022-10-28 12:38 UTC, Munsa1 approved these changes
Hi @Khaled-AlKhateeb, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 12:42 UTC, Khaled-AlKhateeb commented
Thank you!

2022-10-28 12:42 UTC, merged